apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tech-trends-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-staging.yaml 
    path: helm
    repoURL: https://github.com/Oyelowo/tech-trends-app
    targetRevision: HEAD
