apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: web
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
      tag: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
        tag: web
    spec:
      containers:
      - image: oyelowo/techtrends
        imagePullPolicy: IfNotPresent
        name: techtrends
        resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 30
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 20
          timeoutSeconds: 20
        lifecycle:
          postStart:
            exec:
              command: ["python", "init_db.py"]


