apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
  labels:
    app: techtrends
    tag: web
spec:
  ports:
  - name: http
    port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrends
  sessionAffinity: None
  type: ClusterIP
