namespace:
  name: sandbox
service:
  port: 4111

image:
  repository: oyelowo/techtrends
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
hostPath:
  path: /mnt/data/sandbox/database.db
