namespace:
  name: sandbox
service:
  port: 4111
image:
  repository: oyelowo/techtrends
  tag: master-b3550b4b851893336124f3c3f7fff9871de1161c
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
hostPath:
  path: /mnt/data/sandbox/database.db
