name: Tech trends APP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE: techtrends
  IMAGE_TAG: ${GITHUB_REF#refs/heads/}-$GITHUB_SHA
  IMAGE_WITH_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create image name and tag
        run: | 
         echo "IMAGE_WITH_TAG=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
         echo "IMAGE_TAG=${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ${{ env.IMAGE_WITH_TAG }}

      - name: Build and push
        run: |
         docker -v
         docker  build -t oyelowo/techtrends:latest -t oyelowo/techtrends:${{ env.IMAGE_TAG }} .
         docker  push oyelowo/techtrends:latest
         docker  push oyelowo/techtrends:${{ env.IMAGE_TAG }}

  update_image_version:
      name: Deploy
      runs-on: ubuntu-latest
      needs: build

      steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo ${{ env.IMAGE_TAG }}
          TAG=${{env.IMAGE_TAG}} yq e -i '.image.tag = strenv(TAG)' helm/values.yaml
          cat helm/values.yaml
          
      - name: Commit files
        run: |
          git config --local user.email "oyelowooyedayo@gmail.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump docker tag"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
